name: CI/CD Pipeline - Com

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test --if-present

      - name: Faire le build
        run: npm run build || true

  deploy:
    needs: build-and-check
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur la VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/manalmrbt/Desktop/projets/App-Ytech-Solutions-Commerce
            git pull origin main
            npm install
            npm run build || true
            pm2 restart App-Ytech-Solutions-Commerce || pm2 start npm --name "App-Ytech-Solutions-Commerce" -- run dev
